#################
# Key Bindings #
#################
# ctrl-b + r = reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# use ctrl-a as the prefix for accessibility
set -g prefix C-s

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

##################
# Global Config #
##################
set -g mouse on
set -g default-terminal "tmux-256color"
set-option -g history-limit 100000
set -ga terminal-features ",*:hyperlinks"

###########
# Plugins #
###########
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

##############
# Appearance #
##############
set -g @catppuccin_flavor "frappe"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
run '~/.config/tmux/plugins/tpm/tpm'
